# Generated by Django 2.2.1 on 2019-07-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_icons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='icons',
            new_name='icon',
        ),
    ]
